name: Add Closed Source Software
description: Suggest a closed source software to be added to the list
body:
  - type: input
    id: software-name
    attributes:
      label: Software Name
      description: The name of the closed source software
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Official Website
      description: Link to the software's official website
      placeholder: https://example.com
    validations:
      required: true
  - type: input
    id: launch-date
    attributes:
      label: Launch Date
      description: The launch date in YYYY-MM-DD format
      placeholder: "2024-10-29"
    validations:
      required: true
  - type: input
    id: date-source
    attributes:
      label: Launch Date Source
      description: Link to an article, blog post, or announcement that confirms the launch date
      placeholder: https://blog.example.com/launch-announcement
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: If you would like to add any comments or screenshots about the software, please add them here.
